export const GET_USER = 'GET_USER';
export const GET_PROJECT_CATEGORIES = 'GET_PROJECT_CATEGORIES';
export const GET_CATEGORY_PROJECTS = 'GET_CATEGORY_PROJECTS';
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';
