export const GET_USER = 'GET_USER';
export const GET_PROJECT_CATEGORIES = 'GET_PROJECT_CATEGORIES';
export const GET_CATEGORY_PROJECTS = 'GET_CATEGORY_PROJECTS';
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL';
export const GET_ALL_CLAIMED_PROJECTS = 'GET_ALL_CLAIMED_PROJECTS';
export const GET_PROJECT_STAGES = 'GET_PROJECT_STAGES';
export const GET_CLAIMED_PROJECT_STATS = 'GET_CLAIMED_PROJECT_STATS';
